// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: bridge/dex/query.proto

package dex

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName        = "/bridge.dex.Query/Params"
	Query_SellOrder_FullMethodName     = "/bridge.dex.Query/SellOrder"
	Query_SellOrderAll_FullMethodName  = "/bridge.dex.Query/SellOrderAll"
	Query_BuyOrder_FullMethodName      = "/bridge.dex.Query/BuyOrder"
	Query_BuyOrderAll_FullMethodName   = "/bridge.dex.Query/BuyOrderAll"
	Query_DenomTrace_FullMethodName    = "/bridge.dex.Query/DenomTrace"
	Query_DenomTraceAll_FullMethodName = "/bridge.dex.Query/DenomTraceAll"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of SellOrder items.
	SellOrder(ctx context.Context, in *QueryGetSellOrderRequest, opts ...grpc.CallOption) (*QueryGetSellOrderResponse, error)
	SellOrderAll(ctx context.Context, in *QueryAllSellOrderRequest, opts ...grpc.CallOption) (*QueryAllSellOrderResponse, error)
	// Queries a list of BuyOrder items.
	BuyOrder(ctx context.Context, in *QueryGetBuyOrderRequest, opts ...grpc.CallOption) (*QueryGetBuyOrderResponse, error)
	BuyOrderAll(ctx context.Context, in *QueryAllBuyOrderRequest, opts ...grpc.CallOption) (*QueryAllBuyOrderResponse, error)
	// Queries a list of DenomTrace items.
	DenomTrace(ctx context.Context, in *QueryGetDenomTraceRequest, opts ...grpc.CallOption) (*QueryGetDenomTraceResponse, error)
	DenomTraceAll(ctx context.Context, in *QueryAllDenomTraceRequest, opts ...grpc.CallOption) (*QueryAllDenomTraceResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SellOrder(ctx context.Context, in *QueryGetSellOrderRequest, opts ...grpc.CallOption) (*QueryGetSellOrderResponse, error) {
	out := new(QueryGetSellOrderResponse)
	err := c.cc.Invoke(ctx, Query_SellOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SellOrderAll(ctx context.Context, in *QueryAllSellOrderRequest, opts ...grpc.CallOption) (*QueryAllSellOrderResponse, error) {
	out := new(QueryAllSellOrderResponse)
	err := c.cc.Invoke(ctx, Query_SellOrderAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BuyOrder(ctx context.Context, in *QueryGetBuyOrderRequest, opts ...grpc.CallOption) (*QueryGetBuyOrderResponse, error) {
	out := new(QueryGetBuyOrderResponse)
	err := c.cc.Invoke(ctx, Query_BuyOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BuyOrderAll(ctx context.Context, in *QueryAllBuyOrderRequest, opts ...grpc.CallOption) (*QueryAllBuyOrderResponse, error) {
	out := new(QueryAllBuyOrderResponse)
	err := c.cc.Invoke(ctx, Query_BuyOrderAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DenomTrace(ctx context.Context, in *QueryGetDenomTraceRequest, opts ...grpc.CallOption) (*QueryGetDenomTraceResponse, error) {
	out := new(QueryGetDenomTraceResponse)
	err := c.cc.Invoke(ctx, Query_DenomTrace_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DenomTraceAll(ctx context.Context, in *QueryAllDenomTraceRequest, opts ...grpc.CallOption) (*QueryAllDenomTraceResponse, error) {
	out := new(QueryAllDenomTraceResponse)
	err := c.cc.Invoke(ctx, Query_DenomTraceAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of SellOrder items.
	SellOrder(context.Context, *QueryGetSellOrderRequest) (*QueryGetSellOrderResponse, error)
	SellOrderAll(context.Context, *QueryAllSellOrderRequest) (*QueryAllSellOrderResponse, error)
	// Queries a list of BuyOrder items.
	BuyOrder(context.Context, *QueryGetBuyOrderRequest) (*QueryGetBuyOrderResponse, error)
	BuyOrderAll(context.Context, *QueryAllBuyOrderRequest) (*QueryAllBuyOrderResponse, error)
	// Queries a list of DenomTrace items.
	DenomTrace(context.Context, *QueryGetDenomTraceRequest) (*QueryGetDenomTraceResponse, error)
	DenomTraceAll(context.Context, *QueryAllDenomTraceRequest) (*QueryAllDenomTraceResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) SellOrder(context.Context, *QueryGetSellOrderRequest) (*QueryGetSellOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellOrder not implemented")
}
func (UnimplementedQueryServer) SellOrderAll(context.Context, *QueryAllSellOrderRequest) (*QueryAllSellOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellOrderAll not implemented")
}
func (UnimplementedQueryServer) BuyOrder(context.Context, *QueryGetBuyOrderRequest) (*QueryGetBuyOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyOrder not implemented")
}
func (UnimplementedQueryServer) BuyOrderAll(context.Context, *QueryAllBuyOrderRequest) (*QueryAllBuyOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyOrderAll not implemented")
}
func (UnimplementedQueryServer) DenomTrace(context.Context, *QueryGetDenomTraceRequest) (*QueryGetDenomTraceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DenomTrace not implemented")
}
func (UnimplementedQueryServer) DenomTraceAll(context.Context, *QueryAllDenomTraceRequest) (*QueryAllDenomTraceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DenomTraceAll not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SellOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSellOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SellOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SellOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SellOrder(ctx, req.(*QueryGetSellOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SellOrderAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSellOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SellOrderAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SellOrderAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SellOrderAll(ctx, req.(*QueryAllSellOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BuyOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBuyOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BuyOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_BuyOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BuyOrder(ctx, req.(*QueryGetBuyOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BuyOrderAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllBuyOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BuyOrderAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_BuyOrderAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BuyOrderAll(ctx, req.(*QueryAllBuyOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DenomTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDenomTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DenomTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DenomTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DenomTrace(ctx, req.(*QueryGetDenomTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DenomTraceAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDenomTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DenomTraceAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DenomTraceAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DenomTraceAll(ctx, req.(*QueryAllDenomTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.dex.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "SellOrder",
			Handler:    _Query_SellOrder_Handler,
		},
		{
			MethodName: "SellOrderAll",
			Handler:    _Query_SellOrderAll_Handler,
		},
		{
			MethodName: "BuyOrder",
			Handler:    _Query_BuyOrder_Handler,
		},
		{
			MethodName: "BuyOrderAll",
			Handler:    _Query_BuyOrderAll_Handler,
		},
		{
			MethodName: "DenomTrace",
			Handler:    _Query_DenomTrace_Handler,
		},
		{
			MethodName: "DenomTraceAll",
			Handler:    _Query_DenomTraceAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bridge/dex/query.proto",
}
